micronaut:
  application:
    name: hex
  server:
    port: 8082

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
    schema-generate: CREATE_DROP
    schema-generate-names:
      - roles

logger:
  levels:
    co.onmind.hex: DEBUG
    io.micronaut.data: DEBUG
    io.micronaut.web: DEBUG
    io.micronaut.http: DEBUG